# -*- coding: utf-8 -*-
"""Graph based model for fraud detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PCjS4UowFPObhCTC7uzCpixEXG6MLm8x
"""

import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore') # To ignore all warnings
warnings.filterwarnings('ignore', category=UserWarning) # To ignore specific category

np.random.seed(42)  # for reproducibility

n_entities = 1000
n_transactions = 5000

# Create synthetic entity IDs
entities = [f"User_{i}" for i in range(n_entities)]

# Randomly generate transactions
df_large = pd.DataFrame({
    'sender': np.random.choice(entities, n_transactions),
    'receiver': np.random.choice(entities, n_transactions),
    'amount': np.round(np.random.exponential(scale=1000, size=n_transactions), 2),
    'timestamp': pd.to_datetime('2023-01-01') + pd.to_timedelta(np.random.randint(0, 180, size=n_transactions), unit='D')
})

# Remove self-transfers
df_large = df_large[df_large['sender'] != df_large['receiver']].reset_index(drop=True)

print(df_large.head())
print(f"Total transactions: {len(df_large)}")

df_large['day'] = df_large['timestamp'].dt.date
daily_graphs = {day: df_large[df_large['day'] == day] for day in df_large['day'].unique()}

display(daily_graphs)

# build graph

import networkx as nx

G = nx.from_pandas_edgelist(
    df_large,
    source='sender',
    target='receiver',
    edge_attr=['amount', 'timestamp'],
    create_using=nx.DiGraph()
)
print(f"Graph has {G.number_of_nodes()} nodes and {G.number_of_edges()} edges")


# Note:
# Node	A point or entity in the network
# Edge	A connection or relationship between nodes
# Node: A bank account or customer
# Edge: A wire transfer between accounts
# Node: A user
# Edge: A friendship or message

# Engineer Features and Train a Model

# Add a circular fraud ring
ring_entities = [f"Fraud_{i}" for i in range(10)]
ring_tx = []

for i in range(len(ring_entities)):
    sender = ring_entities[i]
    receiver = ring_entities[(i + 1) % len(ring_entities)]
    ring_tx.append({
        'sender': sender,
        'receiver': receiver,
        'amount': np.random.randint(5000, 20000),
        'timestamp': pd.to_datetime('2023-03-01')
    })

# Inject into main dataset
df_large = pd.concat([df_large, pd.DataFrame(ring_tx)], ignore_index=True)

display(df_large)

# Create Pyvis Graph

# Inject synthetic fraud ring
fraud_ring_ids = [f"User_{900 + i}" for i in range(10)]
fraud_transactions = []

for i in range(len(fraud_ring_ids)):
    fraud_transactions.append({
        'sender': fraud_ring_ids[i],
        'receiver': fraud_ring_ids[(i + 1) % len(fraud_ring_ids)],
        'amount': 9999.99,
        'timestamp': pd.Timestamp('2023-03-01')
    })

# Add fraud to the main DataFrame
df_fraud = pd.DataFrame(fraud_transactions)
df_large = pd.concat([df_large, df_fraud], ignore_index=True).reset_index(drop=True)

# Flag fraud
df_large['is_fraud'] = False
df_large.loc[df_large.index[-len(fraud_transactions):], 'is_fraud'] = True

display(df_large.head())

!pip install pyvis -q
import pandas as pd
import numpy as np
from pyvis.network import Network
from IPython.display import HTML

# Step 1: Create large transaction dataset
np.random.seed(42)
n_entities = 1000
n_transactions = 5000
entities = [f"User_{i}" for i in range(n_entities)]

df_large = pd.DataFrame({
    'sender': np.random.choice(entities, n_transactions),
    'receiver': np.random.choice(entities, n_transactions),
    'amount': np.round(np.random.exponential(scale=1000, size=n_transactions), 2),
    'timestamp': pd.to_datetime('2023-01-01') + pd.to_timedelta(np.random.randint(0, 180, size=n_transactions), unit='D')
})
df_large = df_large[df_large['sender'] != df_large['receiver']].reset_index(drop=True)

# Step 2: Inject synthetic fraud ring
fraud_ring_ids = [f"User_{900 + i}" for i in range(10)]
fraud_transactions = [{
    'sender': fraud_ring_ids[i],
    'receiver': fraud_ring_ids[(i + 1) % len(fraud_ring_ids)],
    'amount': 9999.99,
    'timestamp': pd.Timestamp('2023-03-01')
} for i in range(len(fraud_ring_ids))]

df_fraud = pd.DataFrame(fraud_transactions)
df_large = pd.concat([df_large, df_fraud], ignore_index=True)
df_large['is_fraud'] = False
df_large.loc[df_large.index[-len(fraud_transactions):], 'is_fraud'] = True

# Step 3: Sample for visualization
df_sample = pd.concat([
    df_large[df_large['is_fraud']],
    df_large[~df_large['is_fraud']].sample(200, random_state=42)
])

# Step 4: Create interactive graph
net = Network(height="700px", width="100%", directed=True, notebook=True, cdn_resources='remote')
for _, row in df_sample.iterrows():
    edge_color = "red" if row['is_fraud'] else "green"
    net.add_node(row['sender'], label=row['sender'], color='orange')
    net.add_node(row['receiver'], label=row['receiver'], color='orange')
    net.add_edge(row['sender'], row['receiver'], color=edge_color, title=f"${row['amount']}")

# Step 5: Save and Display manually to avoid connection errors
net.save_graph("fraud_detection_network.html")
HTML(filename="fraud_detection_network.html")

import pandas as pd
import numpy as np
from pyvis.network import Network
from IPython.display import HTML

# Step 1: Create large transaction dataset
np.random.seed(42)
n_entities = 1000
n_transactions = 5000
entities = [f"User_{i}" for i in range(n_entities)]

df_large = pd.DataFrame({
    'sender': np.random.choice(entities, n_transactions),
    'receiver': np.random.choice(entities, n_transactions),
    'amount': np.round(np.random.exponential(scale=1000, size=n_transactions), 2),
    'timestamp': pd.to_datetime('2023-01-01') + pd.to_timedelta(np.random.randint(0, 180, size=n_transactions), unit='D')
})
df_large = df_large[df_large['sender'] != df_large['receiver']].reset_index(drop=True)

# Step 2: Inject synthetic fraud ring
fraud_ring_ids = [f"User_{900 + i}" for i in range(10)]
fraud_transactions = [{
    'sender': fraud_ring_ids[i],
    'receiver': fraud_ring_ids[(i + 1) % len(fraud_ring_ids)],
    'amount': 9999.99,
    'timestamp': pd.Timestamp('2023-03-01')
} for i in range(len(fraud_ring_ids))]

df_fraud = pd.DataFrame(fraud_transactions)
df_large = pd.concat([df_large, df_fraud], ignore_index=True)
df_large['is_fraud'] = False
df_large.loc[df_large.index[-len(fraud_transactions):], 'is_fraud'] = True

# Step 3: Sample for visualization
df_sample = pd.concat([
    df_large[df_large['is_fraud']],
    df_large[~df_large['is_fraud']].sample(200, random_state=42)
])

# Step 4: Create interactive graph
net = Network(height="700px", width="100%", directed=True, notebook=True, cdn_resources='remote')
# Track nodes we've already added
added_nodes = set()

for _, row in df_sample.iterrows():
    edge_color = "red" if row['is_fraud'] else "green"

    for node in [row['sender'], row['receiver']]:
        if node not in added_nodes:
            # Check if this node appears in any fraud transaction
            is_fraud_node = df_sample[
                ((df_sample['sender'] == node) | (df_sample['receiver'] == node)) &
                (df_sample['is_fraud'])
            ].any().any()

            node_color = "red" if is_fraud_node else "green"
            net.add_node(node, label=node, color=node_color)
            added_nodes.add(node)

    net.add_edge(row['sender'], row['receiver'], color=edge_color, title=f"${row['amount']}")

# Step 5: Save and Display
net.save_graph("fraud_detection_network.html")
HTML(filename="fraud_detection_network.html")

import pandas as pd
import numpy as np
from pyvis.network import Network
from IPython.display import HTML

# Step 1: Create large transaction dataset
np.random.seed(42)
n_entities = 1000
n_transactions = 5000
entities = [f"User_{i}" for i in range(n_entities)]

df_large = pd.DataFrame({
    'sender': np.random.choice(entities, n_transactions),
    'receiver': np.random.choice(entities, n_transactions),
    'amount': np.round(np.random.exponential(scale=1000, size=n_transactions), 2),
    'timestamp': pd.to_datetime('2023-01-01') + pd.to_timedelta(np.random.randint(0, 180, size=n_transactions), unit='D')
})
df_large = df_large[df_large['sender'] != df_large['receiver']].reset_index(drop=True)

# Step 2: Inject synthetic fraud ring
fraud_ring_ids = [f"User_{900 + i}" for i in range(10)]
fraud_transactions = [{
    'sender': fraud_ring_ids[i],
    'receiver': fraud_ring_ids[(i + 1) % len(fraud_ring_ids)],
    'amount': 9999.99,
    'timestamp': pd.Timestamp('2023-03-01')
} for i in range(len(fraud_ring_ids))]

df_fraud = pd.DataFrame(fraud_transactions)
df_large = pd.concat([df_large, df_fraud], ignore_index=True)
df_large['is_fraud'] = False
df_large.loc[df_large.index[-len(fraud_transactions):], 'is_fraud'] = True

# Step 3: Sample for visualization
df_sample = pd.concat([
    df_large[df_large['is_fraud']],
    df_large[~df_large['is_fraud']].sample(200, random_state=42)
])

# Sum of amounts sent + received per user in the sample
node_amounts = (
    df_sample.groupby('sender')['amount'].sum().add(
    df_sample.groupby('receiver')['amount'].sum(), fill_value=0)
)

# Step 4: Create interactive graph
net = Network(height="700px", width="100%", directed=True, notebook=True, cdn_resources='remote')
added_nodes = set()

for _, row in df_sample.iterrows():
    edge_color = "red" if row['is_fraud'] else "green"

    for node in [row['sender'], row['receiver']]:
        if node not in added_nodes:
            is_fraud_node = df_sample[
                ((df_sample['sender'] == node) | (df_sample['receiver'] == node)) &
                (df_sample['is_fraud'])
            ].any().any()

            node_color = "red" if is_fraud_node else "#FFA500" # Orange for normal

            total_amt = node_amounts.get(node, 0)
            node_label = f"{node}\n${total_amt:,.2f}"

            net.add_node(node, label=node_label, color=node_color)
            added_nodes.add(node)

    net.add_edge(row['sender'], row['receiver'], color=edge_color, title=f"${row['amount']}")

# Step 5: Save and Show
net.save_graph("fraud_detection_network.html")
HTML(filename="fraud_detection_network.html")